### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by gregod** [fennerm/snakemake_slurm_utils#1]
I noticed that this code does not have a stated software license.
Would you be willing to release it under an open-source license?

**Comment by fennerm** [comment]
No problem, the project is now under an MIT license. Btw I haven't touched this code in a long time. No idea if it still works.

**Comment by gregod** [comment]
Thanks. It still works!

i include it in my project  https://github.com/gregod/SnakeClusterBox, which packages Slurm and Snakemake into a ram bootable Iso image. Now released under gpl.
